- name: Install Virtualenv
  pip: name=virtualenv

- name: Install Virtualenvwrapper
  pip: name=virtualenvwrapper

- name: Install Jedi
  pip: name=jedi

- name: Install EPC
  pip: name=epc

- name: Install Pycheck
  apt: pkg=pychecker state=present

- name: Install Fabric
  pip: name=fabric

- name: Install Git Review
  pip: name=git-review


